// <auto-generated />
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260224132706_AddStageType")]
    partial class AddStageType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Aggregates.DecisionGraph", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DecisionGraphs");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionGraphProps", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("DecisionGraphId")
                        .HasColumnType("bigint");

                    b.Property<string>("Field")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DecisionGraphId");

                    b.ToTable("DecisionGraphProps");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionOutput", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RuleId");

                    b.ToTable("DecisionOutputs");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("LogicalOperator")
                        .HasColumnType("int");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<long>("StageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("StageId");

                    b.ToTable("DecisionRules");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionRuleCondition", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Operator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PropertyId")
                        .HasColumnType("bigint");

                    b.Property<long>("RuleId")
                        .HasColumnType("bigint");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("RuleId");

                    b.ToTable("DecisionRuleConditions");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionStage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("GraphId")
                        .HasColumnType("bigint");

                    b.Property<int>("HitPolicy")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Priority")
                        .HasColumnType("tinyint");

                    b.Property<int>("StageType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GraphId");

                    b.ToTable("DecisionStages");
                });

            modelBuilder.Entity("Domain.Aggregates.StageConnection", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("FromStageId")
                        .HasColumnType("bigint");

                    b.Property<long>("GraphId")
                        .HasColumnType("bigint");

                    b.Property<long>("ToStageId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("FromStageId");

                    b.HasIndex("ToStageId");

                    b.ToTable("StageConnection");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionGraphProps", b =>
                {
                    b.HasOne("Domain.Aggregates.DecisionGraph", "DecisionGraph")
                        .WithMany("DecisionGraphProps")
                        .HasForeignKey("DecisionGraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DecisionGraph");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionOutput", b =>
                {
                    b.HasOne("Domain.Aggregates.DecisionRule", "Rule")
                        .WithMany("Outputs")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionRule", b =>
                {
                    b.HasOne("Domain.Aggregates.DecisionStage", "Stage")
                        .WithMany("Rules")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionRuleCondition", b =>
                {
                    b.HasOne("Domain.Aggregates.DecisionGraphProps", "Property")
                        .WithMany()
                        .HasForeignKey("PropertyId");

                    b.HasOne("Domain.Aggregates.DecisionRule", "Rule")
                        .WithMany("Conditions")
                        .HasForeignKey("RuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionStage", b =>
                {
                    b.HasOne("Domain.Aggregates.DecisionGraph", "Graph")
                        .WithMany("Stages")
                        .HasForeignKey("GraphId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Graph");
                });

            modelBuilder.Entity("Domain.Aggregates.StageConnection", b =>
                {
                    b.HasOne("Domain.Aggregates.DecisionStage", "FromStage")
                        .WithMany("OutgoingConnections")
                        .HasForeignKey("FromStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Aggregates.DecisionStage", "ToStage")
                        .WithMany("IncomingConnections")
                        .HasForeignKey("ToStageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromStage");

                    b.Navigation("ToStage");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionGraph", b =>
                {
                    b.Navigation("DecisionGraphProps");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionRule", b =>
                {
                    b.Navigation("Conditions");

                    b.Navigation("Outputs");
                });

            modelBuilder.Entity("Domain.Aggregates.DecisionStage", b =>
                {
                    b.Navigation("IncomingConnections");

                    b.Navigation("OutgoingConnections");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
